In [1]:
import pandas as pd

In [ ]:
dados = {
    'nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'idade': [25, 30, 35, 28],
    'cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Curitiba']}

dados

{'nome': ['João', 'Maria', 'Pedro', 'Ana'],
 'idade': [25, 30, 35, 28],
 'cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Curitiba']}

In [3]:
df = pd.DataFrame(dados)

In [4]:
df

    nome  idade          cidade
0   João     25       São Paulo
1  Maria     30  Rio de Janeiro
2  Pedro     35  Belo Horizonte
3    Ana     28        Curitiba

In [8]:
dados_notas = {
    'nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Matematica': [8.5, 9.0, 7.5, 8.0],
    'Portugues': [7.0, 8.5, 9.0, 7.5],
    'Historia': [9.0, 8.0, 7.5, 8.5],
    'Fisica': [8.0, 7.5, 9.0, 8.5],}

df_notas = pd.DataFrame(dados_notas)
df_notas

    nome  Matematica  Portugues  Historia  Fisica
0   João         8.5        7.0       9.0     8.0
1  Maria         9.0        8.5       8.0     7.5
2  Pedro         7.5        9.0       7.5     9.0
3    Ana         8.0        7.5       8.5     8.5

In [11]:
#Calculando a média das notas
df_notas['Media'] = df_notas[['Matematica', 'Portugues', 'Historia', 'Fisica']].mean(axis=1)

df_notas

    nome  Matematica  Portugues  Historia  Fisica  Media
0   João         8.5        7.0       9.0     8.0  8.125
1  Maria         9.0        8.5       8.0     7.5  8.250
2  Pedro         7.5        9.0       7.5     9.0  8.250
3    Ana         8.0        7.5       8.5     8.5  8.125

In [12]:
df_notas[['nome', 'Media']].sort_values(by='Media', ascending=False)

    nome  Media
1  Maria  8.250
2  Pedro  8.250
0   João  8.125
3    Ana  8.125